function coverslipLabelled = importCoverslip(filename, dataLines)
%IMPORTFILE Import data from a text file
%  COVERSLIPLABELLED = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  COVERSLIPLABELLED = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  coverslipLabelled = importfile("G:\Data\CRUK MDPA\dotphotonCompressed\temp\20190614_CRUK15\main488_642\19-06-14\15-23-19\cst4\activeContourAndOtusSegmentation\stats\coverslipLabelled.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-Jan-2021 10:51:44

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 54);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Volume_cell", "EquivDiameter_cell", "SurfaceArea_cell", "MeanIntensity", "MinIntensity", "MaxIntensity", "MajorAxis_cell", "MinorAxis_cell", "secondMajor_cell", "Eccentricity_cell", "secondEccentricity_cell", "Sphericity_cell", "Vol2surf_cell", "runNumber", "timeTrack", "yDim", "xDim", "zDim", "xCoord_cell", "yCoord_cell", "zCoord_cell", "Orbit", "AngleBetween", "serialNumber", "fieldNumber", "Treatment", "Row", "Column", "Polarity_cell", "Spreading_cell", "Protrusivity_cell", "cellNumber", "NucleusVolumeFraction", "Volume_nucleus", "EquivDiameter_nucleus", "SurfaceArea_nucleus", "MajorAxis_nucleus", "MinorAxis_nucleus", "secondMajor_nucleus", "Eccentricity_nucleus", "secondEccentricity_nucleus", "Sphericity_nucleus", "Vol2surf_nucleus", "xCoord_nucleus", "yCoord_nucleus", "zCoord_nucleus", "Polarity_nucleus", "Spreading_nucleus", "Protrusivity_nucleus", "Plate", "height", "percentFiltered", "coverslip", "coverslipDistance", "onCoverslip"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "double", "string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["serialNumber", "Treatment", "Row"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["serialNumber", "Treatment", "Row", "onCoverslip"], "EmptyFieldRule", "auto");

% Import the data
coverslipLabelled = readtable(filename, opts);

t = coverslipLabelled.onCoverslip;
p = zeros(size(t));
p(strcmp(t, "True")) = 1;

coverslipLabelled.cluster = p;

end