function all = importClusterTableNew(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ALL = IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  ALL = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  all = importfile("G:\Data\CRUK MDPA\dotphotonCompressed\temp\20190815_CRUK21_liveDrug\main488_642\19-08-15\15-48-27\cst4\activeContourAndOtusSegmentation\stats\pcaData\clusterData\all.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Jan-2021 08:17:06

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 33);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["principalComponent1", "principalComponent2", "principalComponent3", "principalComponent4", "principalComponent5", "runNumber", "timeTrack", "fieldNumber", "Row", "Column", "Treatment", "cellNumber", "serialNumber", "MeanIntensity", "MinIntensity", "MaxIntensity", "yDim", "xDim", "zDim", "height", "percentFiltered", "coverslip", "coverslipDistance", "onCoverslip", "percentOnCoverslip", "Plate", "xCoord_cell", "yCoord_cell", "zCoord_cell", "xCoord_nucleus", "yCoord_nucleus", "zCoord_nucleus", "cluster"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "categorical", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "serialNumber", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Row", "Treatment", "serialNumber", "onCoverslip"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["principalComponent1", "principalComponent2", "principalComponent3", "principalComponent4", "principalComponent5", "runNumber", "timeTrack", "fieldNumber", "Column", "cellNumber", "MeanIntensity", "MinIntensity", "MaxIntensity", "yDim", "xDim", "zDim", "height", "percentFiltered", "coverslip", "coverslipDistance", "percentOnCoverslip", "Plate", "xCoord_cell", "yCoord_cell", "zCoord_cell", "xCoord_nucleus", "yCoord_nucleus", "zCoord_nucleus", "cluster"], "ThousandsSeparator", ",");

% Import the data
all = readtable(filename, opts);

end